### PR TITLE
Support to ignore network adapters used for ICE on Android, iOS and MacOS.

### PR DESCRIPTION
**Pull request by MohamedRisaldarTA**
Will solve https://github.com/flutter-webrtc/flutter-webrtc/issues/1389

### CODE REVIEW

**Comment by MohamedRisaldarTA** [comment]
> Will solve #1389

Waiting for release including https://github.com/webrtc-sdk/webrtc/pull/78

**Comment by cloudwebrtc** [comment]
@MohamedRisaldarTA https://github.com/webrtc-sdk/android/releases/tag/v114.5735.02

**Comment by MohamedRisaldarTA** [comment]
> @MohamedRisaldarTA https://github.com/webrtc-sdk/android/releases/tag/v114.5735.02

Thanks, I was watching in between.

**Review by cloudwebrtc — APPROVED** [review]
lgtm

**Pull request merged**
