### PR TITLE
set the specified MediaStream trackId

### PR DESCRIPTION
**Pull request by TBYSKY**

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
hi @TBYSKY, What is the intent of doing this? so, under what conditions will a MediaStream contain multiple video tracks

**Comment by TBYSKY** [comment]
When sending webcam video and screen sharing video at the same time

**Comment by TBYSKY** [comment]
I have rolled back the code and added  compatibility for Flutter Web

**Review by cloudwebrtc — APPROVED** [review]
lgtm

**Pull request merged**
