### PR TITLE
Fix for Issue #409, including updating example project to run on Android 10.

### PR DESCRIPTION
**Pull request by admarwick**
Fixes [Issue #409](https://github.com/flutter-webrtc/flutter-webrtc/issues/409), and updates the example to run on Android 10.

- Fix [Issue #409](https://github.com/flutter-webrtc/flutter-webrtc/issues/409) by adding a null guard
to `com.cloudwebrtc.webrtc/MedhodCallHandler.java`, case "startRecordToFile".
- Update the example project with the ForegroundService needed to run it on Android 10.

### CODE REVIEW

**Review by cloudwebrtc — CHANGES_REQUESTED** [review]
Please remove `example/android/*/*` related files.

The example native project is created using scripts, and project files should be avoided in the example.

Please add `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` into:
https://github.com/flutter-webrtc/flutter-webrtc/blob/master/example/scripts/project_tools.sh#L47.

**Comment by admarwick** [comment]
I'm not at all familiar with Pull Requests, and I'm not sure I was able remove the example files from it. Any advice would be appreciated.

**Comment by cloudwebrtc** [comment]
@admarwick It looks very close now, just restores the deleted `example/lib/main.dart`.

**Comment by cloudwebrtc** [comment]
LGTM

**Pull request merged**
