### PR TITLE
Improve publishing for pull request

### PR DESCRIPTION
**Pull request by tyranron**

### CODE REVIEW

**Comment by tyranron** [comment]
Sorry, mistake. Please, delete this.

**Comment by ycherniavskyi** [comment]
@tyranron please fill GitHub support request by yourself - https://stackoverflow.com/a/18318431/9967488.

**Comment by ycherniavskyi** [comment]
Hmm, it seems that only owner could do this. Ok I will create support request.

**Comment by ycherniavskyi** [comment]
@cloudwebrtc it seems that your assistance needs here:
image

**Comment by cloudwebrtc** [comment]
hey @ycherniavskyi, Is this a robot? How do I need to set it up?

**Comment by ycherniavskyi** [comment]
@cloudwebrtc https://support.github.com/request/remove-data -> Remove pull requests

**Pull request closed without merging**
