### PR TITLE
feat: Add support for  linux desktop (will be supported in release 1.0).

### LINKED ISSUE #37: [WIP]Support for Flutter Desktop
Texture widget for the embedder seems to be coming soon: https://github.com/google/flutter-desktop-embedding/issues/107#issuecomment-444272681, let's port it to the desktop embedder and let the plugin extend to mac/linux/windows.  😄

### LINKED ISSUE #234: **Screen/Window Capture for Linux**

### LINKED ISSUE #492: Support for desktop linux version
Waiting for the Linux desktop version.

### LINKED ISSUE #729: Support Embedded Linux
Support for embedded devices. It can be used in industrial, robotics, VOIP desktop hardware，or AI/ML edge devices.
https://github.com/sony/flutter-embedded-linux

### PR DESCRIPTION
**Pull request by cloudwebrtc**
close #729, close #492, close #37, close #234

### CODE REVIEW

**Comment by TheOneWithTheBraid** [comment]
May in kindly ask for the status of this PR? I saw it is opened for more than half a year. Do you have a roadmap about its release date? Thanks a lot for some information.

**Review by webbeon — APPROVED** [review]

**Comment by jeaye** [comment]
This is superb! Thanks for cooking this up; I'm eager to see this merged. Can any of us help push this across the finish line?

**Comment by cloudwebrtc** [comment]
The good news is that I have successfully run flutter-webrtc on Sony's flutter-elinux https://github.com/flutter-webrtc/flutter-webrtc/pull/741, and what I need to do in this branch is to create a layer of adaptation code to shield the calling differences between windows/linux. I think the code is completely Compatible. It will work perfectly as flutter-elinux.

**Comment by provokateurin** [comment]
Hello, I'm very interested in this PR and help if possible. Anything I/we can do to support you @cloudwebrtc in this effort?

**Comment by cloudwebrtc** [comment]
hey @provokateurin, I think the completion of this PR is 60-70%. I used the binary_messenger of flutter linux to forge a C++ API bridge that is consistent with the flutter windows client. It can work now, but it will encounter memory release problems. I have been busy recently and have not continued. Debug it, if you are interested, you can try to clone this branch to debug.

**Comment by provokateurin** [comment]
For now I only have to make a demo, so memory leaks are kind of ok as long as the other stuff works. I'll definitely try fixing stuff if I can

**Comment by cloudwebrtc** [comment]
first working version

**Comment by provokateurin** [comment]
awesome! i'll probably start testing this stuff today

**Comment by cloudwebrtc** [comment]
screen sharing 
image

**Comment by provokateurin** [comment]
I just tested the example on this branch and everything was mostly working, but the trying to screenshare crashed the app. The thumbnails were correctly displayed, but after selecting either a screen or a window it crashed. No debug or crash logs printed to the console

**Comment by cloudwebrtc** [comment]
@provokateurin Please update to the last commit, I fixed the screen sharing crash.

**Comment by provokateurin** [comment]
Can confirm screenshare works now :)

**Comment by provokateurin** [comment]
Awesome work!!! :heart:

**Comment by PeterNjeim** [comment]
It isn't compiling for me on Ubuntu 22.04 WSL2: `<name>/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/linux/flutter/core_implementations.cc:103:10: error: no matching function for call to 'fl_binary_messenger_send_response'`

**Pull request merged**
