### PR TITLE
Implemented features for android

### PR DESCRIPTION
**Pull request by abhay-s-rawat**
Immplemented for android:
created pull request for webrtc_interface 1.0.5

onBufferedAmountChange
bufferedAmount
onBufferedAmountLow
bufferedAmountLowThreshold

### CODE REVIEW

**Review by cloudwebrtc — APPROVED** [review]

**Comment by cloudwebrtc** [comment]
Nice patch, we need to make iOS/Windows support the same before uploading to `pub.dev`.

**Comment by abhay-s-rawat** [comment]
Yes but I need to take a look at ios other platform code and how it is working which might take time because I am not familiar with swift. It was minor update for android because it uses java and I used that a long time ago that's why I was familiar with that code.

**Comment by abhay-s-rawat** [comment]
Can we push changes for android first in git then after adding those features on other platform you can push to pub.dev.

**Comment by cloudwebrtc** [comment]
sure, no problem

**Pull request merged**
