### PR TITLE
Added setZoom method to support camera zooming while streaming.

### PR DESCRIPTION
**Pull request by Jaemin-VIRNECT**
iOS and AOS support (tested on iOS and AOS mobile devices)

How to use?

final videoTrack = _localStream!
        .getVideoTracks()
        .firstWhere((track) => track.kind == 'video');
    await WebRTC.invokeMethod('mediaStreamTrackSetZoom',
        <String, dynamic>{'trackId': videoTrack.id, 'zoomLevel': zoomLevel});
        
        
//After [this PR](https://github.com/flutter-webrtc/webrtc-interface/pull/20) is published. 
(webrtc_interface version needs to be updated  in pubspec.yaml)

await videoTrack.setZoom(zoomLevel);

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
hey @Jaemin-VIRNECT, Tested it out this is a cool feature, but since zoom is only supported on iOS/Android, I recommend adding it to the Helper class https:github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/helper.dart

```dart
class Helper {
....
Future<void> setZoom({MediaStreamTrack videoTrack, double zoomLevel}) {
   if(WebRTC.platformIsAndroid || WebRTC.platformIsiOS) {
       await WebRTC.invokeMethod(
              'mediaStreamTrackSetZoom',
              <String, dynamic>{'trackId': videoTrack.id, 'zoomLevel': zoomLevel},
            );
  } else {
     throw Exception('setZoom only support for mobile devices!');
  }     
}
...
}

await Helper.setZoom(videoTrack, zoomLevel);

```

**Review by cloudwebrtc — APPROVED** [review]
lgtm!

**Comment by Jaemin-VIRNECT** [comment]
Thank you for the fast review.
I will update it soon. 😀

**Comment by cloudwebrtc** [comment]
hey @Jaemin-VIRNECT, Thank you for your PR, I have modified and merged, :)

**Comment by abhinovpankaj** [comment]
How do I use this, I am using flutter_webrtc: ^0.12.6  and webrtc_interface: ^1.2.0 but I get error that setZoom method is notdefined on videoTrack.
image

**Pull request merged**
