### PR TITLE
Switch to custom WebRTC build for iOS

### PR DESCRIPTION
**Pull request by hiroshihorie**
**After we confirm** custom build is stable we should switch to it.

### Q. Should we default to `RTCVideoEncoderFactorySimulcast` ?
I'm not sure if there are any side-effects using `RTCVideoEncoderFactorySimulcast` for non-simulcast mode.

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
@hiroshihorie Can you reopen this PR here? I will merge it and bump the version for flutter-webrtc

**Comment by hiroshihorie** [comment]
@cloudwebrtc Hi, the new WebRTC build will need changes to flutter_webrtc to maintain compatibility with existing users. 
As discussed here https://github.com/webrtc-sdk/webrtc/pull/7
Hopefully in about a week I will implement it and make another PR.

**Comment by marcoberetta96** [comment]
@hiroshihorie may I ask some clarification about this PR?
Why moving from GoogleWebRTC to WebRTC-SDK.

I ask this because for the moment I'm still using flutter_webrtc 0.6.8 because WebRTC-SDK causes a `frameworks with conflicting names` issue on iOS.
Thanks

**Comment by ycherniavskyi** [comment]
GoogleWebRTC pod did not update since Aug 2020.

**Comment by hiroshihorie** [comment]
@marcoberetta96 We moved to WebRTC-SDK because we applied a few patches to benefit users, especially:
- iOS mic related fixes.
- Simulcast.

Can I have more information on how to reproduce the `frameworks with conflicting names` error ?
Are you depending on any other package that uses WebRTC ?

**Comment by marcoberetta96** [comment]
Hi @hiroshihorie 

Yes, I depend on another package that uses WebRTC.

You can have a look by simply install https://pub.dev/packages/flutter_webrtc and https://pub.dev/packages/jitsi_meet and run pod install

**Comment by marcoberetta96** [comment]
@hiroshihorie 
I do not understand if https://github.com/webrtc-sdk/Specs has anything to do with https://cocoapods.org/pods/WebRTC

**Comment by marcoberetta96** [comment]
@hiroshihorie yes, but there's any way to solve this?

**Comment by Yke222** [comment]
Same issue here, any updates on that?

**Pull request closed without merging**
