### PR TITLE
Do not call reStartCamera() for screen capture

### PR DESCRIPTION
**Pull request by XuanTung95**
1.  Fix bug** #551
- Add variable VideoCapturerInfo->isScreenCapture.
- Do not call reStartCamera in case of screen capture

2. Add options "cryptoOptions" when create peerconnection so user can enable Gcm crypto which is much faster.

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
LGTM

**Comment by cloudwebrtc** [comment]
@XuanTung95 Can support `cryptoOptions` for iOS/macOS? I think other platforms also need consistency.

**Comment by cloudwebrtc** [comment]
Has been added in this commit.
https://github.com/flutter-webrtc/flutter-webrtc/commit/d3eaf1698fa7c302fd41215be20905efeb20991e#diff-2496b27d4acaf6c7dc7482b1b221ccc92d20f720d1ca50d9aaffa404f0306564R1218

**Comment by XuanTung95** [comment]
> @XuanTung95 Can support `cryptoOptions` for iOS/macOS? I think other platforms also need consistency.

Idk, I only develop on Android.

**Pull request merged**
