### PR TITLE
New video constraints syntax

### PR DESCRIPTION
**Pull request by davidliu**
Updating getUserMedia to use latest video constraint syntax (https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints).

Current getUserMedia constraints have been deprecated for years (and documentation is very sparse), so we should start looking to support the latest syntax.

### CODE REVIEW

**Comment by davidliu** [comment]
The PR currently only contains Android changes at the moment, but will update with changes for the other platforms; mainly requesting for comments rather than approval until then. 

The PR only handles the `ideal` property, and won't support min/max right now (as that requires quite a bit more work).

**Comment by davidliu** [comment]
This should now cover all the currently supported platforms (web already handles the latest syntax).

**Comment by davidzhao** [comment]
@cloudwebrtc @hiroshihorie please take a look at this PR. It resolves inconsistencies in media constraint specification. the PR is backwards compatible

**Comment by hiroshihorie** [comment]
Nice update!

**Comment by cloudwebrtc** [comment]
LGTM

**Review by cloudwebrtc — APPROVED** [review]

**Pull request merged**
