### PR TITLE
feat: Add support for elinux.

### PR DESCRIPTION
**Pull request by cloudwebrtc**
~Currently, it can be compiled and run, But cross-thread calls will cause a crash, so need debugging.~

Update:
The crash just happens in debug mode, everything works fine in release/profile mode

In debug mode, it seems that the problem occurs with asserts caused by cross-thread calls
````
[FATAL:flutter/fml/memory/weak_ptr.h(111)] Check failed: (checker_.checker).IsCreationThreadCurrent().
````

image

### CODE REVIEW

**Comment by seanchann** [comment]
any news?  I think if it is for the arm architecture, does it need to be implemented based on `Gstreamer/webrtcbin` or another portable engineering for embedded os? (current libwebrtc file  is x86 binary )

**Comment by cloudwebrtc** [comment]
Embedded Linux can use v4l2, pulse,  alsa, and the google webrtc library is supported, just need to cross-compile this library
https://github.com/webrtc-sdk/libwebrtc

**Comment by cloudwebrtc** [comment]
@seanchann I've added arm/arm64 binaries in subsequent commits

**Comment by cloudwebrtc** [comment]
replace with  https://github.com/flutter-webrtc/flutter-webrtc/pull/1338

**Pull request closed without merging**
